name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy
        uses: burnett01/rsync-deployments@5.2
        with:
          path: ./dist
          remote_path: '/var/www/html/links.letsbenow.de'
          remote_host: host.letsbenow.de
          remote_user: markus
          remote_key: ${{ secrets.PRIVATE_KEY }}
